# Generated by Django 6.0.6 on 2026-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='category',
            field=models.CharField(choices=[('ramp', 'Wheelchair Ramp'), ('tactile', 'Tactile Paving'), ('lift', 'Elevator/Lift'), ('other', 'Other Issue')], default='other', max_length=20),
        ),
    ]
