# Generated by Django 6.0.6 on 2026-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_accessibilityissue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='issues/after/'),
        ),
    ]
