# Generated by Django 6.0.6 on 2026-06-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_accessibilityissue_image_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='community_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessibilityissue',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PROVISIONALLY_RESOLVED', 'Provisionally Resolved (Pending Community Votes)'), ('RESOLVED', 'Permanently Resolved')], default='REPORTED', max_length=30),
        ),
    ]
