# Generated by Django 6.0.6 on 2026-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_profile_communityvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibilityissue',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
