# Generated by Django 6.0.6 on 2026-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_accessibilityissue_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityissue',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibilityissue',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibilityissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
